'use strict';
let token='',items=[],current=null,knowledge=null,pendingFiles=[],busy=false,poll=null;
const el=id=>document.getElementById(id);
const status=message=>{el('status').textContent=message;};
async function api(path,method='GET',body=null){const headers={Authorization:'Bearer '+token};if(body)headers['Content-Type']='application/json';const r=await fetch(path,{method,headers,body:body?JSON.stringify(body):null});if(!r.ok)throw new Error(r.status===409?'This chat changed on another device. Refresh before sending; your draft is retained.':'Request failed ('+r.status+'): '+(await r.text()).slice(0,300));return r.json();}
function safe(action){return async()=>{try{await action();}catch(e){status(e.message);}finally{busy=false;el('send').disabled=false;}};}
function node(tag,text,parent,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;parent.appendChild(n);return n;}
function renderContent(text,parent){const re=/assistant:\/\/artifact\/([a-f0-9]{32})/g;let last=0;for(const m of text.matchAll(re)){parent.appendChild(document.createTextNode(text.slice(last,m.index)));const a=node('a','Download file',parent);a.href='#';a.onclick=safe(async()=>{const r=await fetch('/workspace/files/'+m[1],{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw new Error('Download failed');const blob=await r.blob();const url=URL.createObjectURL(blob);const d=document.createElement('a');d.href=url;d.download=(r.headers.get('Content-Disposition')||'').match(/filename="([^"]+)"/)?.[1]||'assistant-file';d.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});last=m.index+m[0].length;}parent.appendChild(document.createTextNode(text.slice(last)));}
function chats(){el('chats').replaceChildren();const q=el('search').value.toLowerCase();for(const i of items){if(i.deleted||!i.payload.chat)continue;let c;try{c=JSON.parse(i.payload.chat);}catch{continue;}if(!JSON.stringify(c).toLowerCase().includes(q))continue;const b=node('button',c.summary.title,el('chats'),'chat-link');b.onclick=()=>{if(busy)return;current={...i,chat:c};pendingFiles=[];render();};}}
function render(){el('messages').replaceChildren();el('title').textContent=current?.chat.summary.title||'New chat';el('project').replaceChildren();let o=node('option','General chat',el('project'));o.value='';if(knowledge){for(const p of knowledge.value.projects||[]){o=node('option',p.name,el('project'));o.value=p.id;}}el('project').value=current?.chat.summary.projectId||'';for(const m of current?.chat.messages||[]){if(!['user','assistant'].includes(m.role))continue;const box=node('div','',el('messages'),'message');node('div',m.role==='user'?'You':'Assistant',box,'role');renderContent(m.content||'',box);for(const a of m.attachments||[])node('div','Attachment: '+a.name,box);}el('messages').scrollTop=el('messages').scrollHeight;el('attachments').textContent=pendingFiles.map(a=>a.name).join(', ');el('memories').replaceChildren();for(const m of knowledge?.value.memories||[]){const box=node('div',m.text,el('memories'),'memory');const remove=node('button','Forget',box);remove.onclick=safe(async()=>{const next=structuredClone(knowledge.value);next.memories=next.memories.filter(x=>x.id!==m.id);await saveKnowledge(next);});}}
async function saveKnowledge(next){const i=await api('/workspace/items/knowledge','PUT',{revision:knowledge?.revision||0,payload:{knowledge:JSON.stringify(next)}});knowledge={revision:i.revision,value:next};await refresh();}
async function refresh(){items=await api('/workspace/items');const k=items.find(i=>i.id==='knowledge'&&!i.deleted);knowledge=k?{revision:k.revision,value:JSON.parse(k.payload.knowledge)}:null;if(current){const latest=items.find(i=>i.id===current.id&&!i.deleted);if(latest)current={...latest,chat:JSON.parse(latest.payload.chat)};}chats();render();const jobs=await api('/workspace/jobs');el('jobs').replaceChildren();for(const j of jobs.slice(0,15)){const box=node('div',j.prompt+'\n'+j.status,el('jobs'),'task');if(j.result)renderContent('\n'+j.result,box);if(j.error)node('div',j.error,box);for(const action of (['scheduled','running'].includes(j.status)?['pause','cancel']:['paused','failed'].includes(j.status)?['resume','cancel','delete']:['delete'])){const b=node('button',action,box);b.onclick=safe(async()=>{await api('/workspace/jobs/'+j.id+(action==='delete'?'':'/'+action),action==='delete'?'DELETE':'POST');await refresh();});}}status('Connected. Phone sync is available under Workspace → Sync now.');}
el('connect').onclick=safe(async()=>{token=el('token').value.trim();await refresh();el('token').value='';el('login').hidden=true;el('workspace').hidden=false;});
el('refresh').onclick=safe(refresh);el('search').oninput=chats;
el('new').onclick=()=>{if(busy)return;current=null;pendingFiles=[];el('draft').value='';render();};
el('lock').onclick=()=>{token='';items=[];current=null;knowledge=null;pendingFiles=[];clearInterval(poll);el('draft').value='';el('messages').replaceChildren();el('jobs').replaceChildren();el('memories').replaceChildren();el('workspace').hidden=true;el('login').hidden=false;status('Locked');};
el('send').onclick=safe(async()=>{const draft=el('draft').value.trim();if(busy||(!draft&&!pendingFiles.length))return;busy=true;el('send').disabled=true;const now=Date.now();const id=current?.id||crypto.randomUUID();const c=structuredClone(current?.chat||{version:1,summary:{id,title:draft.slice(0,70)||'Files',createdAt:now,updatedAt:now},messages:[]});c.summary.updatedAt=now;c.summary.projectId=el('project').value||null;c.messages.push({role:'user',content:draft,attachments:pendingFiles});const job=await api('/workspace/items/'+id+'/continue','POST',{revision:current?.revision||0,payload:{chat:JSON.stringify(c)}});current={id,revision:job.revision,chat:c};pendingFiles=[];el('draft').value='';render();status('Working on the computer…');clearInterval(poll);poll=setInterval(safe(async()=>{const jobs=await api('/workspace/jobs');const j=jobs.find(x=>x.id===job.id);if(j&&!['running','scheduled'].includes(j.status)){clearInterval(poll);await refresh();status(j.error||'Reply ready');}}),4000);});
el('schedule').onclick=safe(async()=>{const prompt=el('draft').value.trim();if(!prompt)return;await api('/workspace/jobs','POST',{prompt});el('draft').value='';await refresh();status('Background task queued. Refresh to see results.');});
el('saveMemory').onclick=safe(async()=>{const text=el('memory').value.trim();if(!text)return;const next=structuredClone(knowledge?.value||{memories:[],projects:[]});next.memories.push({id:crypto.randomUUID(),text,updatedAt:Date.now()});await saveKnowledge(next);el('memory').value='';});
el('file').onchange=safe(async()=>{const f=el('file').files[0];if(!f)return;if(f.size>25*1024*1024)throw new Error('File exceeds 25 MB');const r=await fetch('/workspace/files',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':f.type||'application/octet-stream','X-File-Name':encodeURIComponent(f.name)},body:f});if(!r.ok)throw new Error('Upload failed ('+r.status+')');const info=await r.json();const a={id:crypto.randomUUID(),name:f.name,mimeType:f.type||'application/octet-stream',remoteFileId:info.id,kind:f.type.startsWith('image/')?'image':'document',path:'remote:'+info.id};if(a.kind==='document'){const e=await fetch('/extract',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':a.mimeType,'X-Filename':encodeURIComponent(f.name)},body:f});if(e.ok){const extracted=await e.json();a.text=extracted.text||'';a.note=extracted.note||'';}}pendingFiles.push(a);render();el('file').value='';});
